#!/usr/bin/env python3
"""
Secret Management Utility for Legate Studio

Generates and manages secrets in .env file.
Supports interactive setup for GitHub OAuth and LEGATO configuration.
"""
import secrets
import os
from pathlib import Path

# Required environment variables for Legate Studio
ENV_VARS = {
    'FLASK_SECRET_KEY': {
        'description': 'Flask session secret key',
        'generator': lambda: secrets.token_hex(32),
        'required': True
    },
    'FLASK_ENV': {
        'description': 'Environment (development/production)',
        'default': 'production',
        'required': True
    },
    'GITHUB_CLIENT_ID': {
        'description': 'GitHub OAuth App Client ID',
        'required': True
    },
    'GITHUB_CLIENT_SECRET': {
        'description': 'GitHub OAuth App Client Secret',
        'required': True
    },
    'GITHUB_ALLOWED_USERS': {
        'description': 'Comma-separated list of allowed GitHub usernames',
        'required': True
    },
    'SYSTEM_PAT': {
        'description': 'GitHub PAT for API access (needs repo scope)',
        'required': True
    },
    'LEGATO_ORG': {
        'description': 'GitHub organization/user for LEGATO repos',
        'default': 'bobbyhiddn',
        'required': False
    },
    'CONDUCT_REPO': {
        'description': 'LEGATO Conduct repository name',
        'default': 'Legato.Conduct',
        'required': False
    }
}


def load_env_file(env_path: Path) -> dict:
    """Load existing .env file into a dictionary."""
    env_vars = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, _, value = line.partition('=')
                    env_vars[key.strip()] = value.strip()
    return env_vars


def save_env_file(env_path: Path, env_vars: dict):
    """Save dictionary to .env file."""
    with open(env_path, 'w') as f:
        f.write("# Legate Studio Configuration\n")
        f.write("# Generated by flask_keygen.py\n\n")

        for key, config in ENV_VARS.items():
            if key in env_vars:
                f.write(f"# {config['description']}\n")
                f.write(f"{key}={env_vars[key]}\n\n")


def interactive_setup():
    """Interactive setup for all required environment variables."""
    env_path = Path('.env')
    env_vars = load_env_file(env_path)

    print("\n=== Legate Studio Configuration Setup ===\n")

    for key, config in ENV_VARS.items():
        current = env_vars.get(key, '')
        desc = config['description']

        # Auto-generate if generator provided and no current value
        if 'generator' in config and not current:
            env_vars[key] = config['generator']()
            print(f"[AUTO] {key}: Generated new secret")
            continue

        # Use default if provided
        default = config.get('default', '')
        prompt = f"{desc}"
        if current:
            prompt += f" [current: {current[:20]}...]" if len(current) > 20 else f" [current: {current}]"
        elif default:
            prompt += f" [default: {default}]"

        prompt += ": "

        value = input(prompt).strip()

        if not value:
            if current:
                value = current
            elif default:
                value = default
            elif config.get('required'):
                print(f"  ERROR: {key} is required!")
                continue

        if value:
            env_vars[key] = value

    save_env_file(env_path, env_vars)
    print(f"\nConfiguration saved to {env_path}")
    print("\nNext steps:")
    print("  1. Review the .env file")
    print("  2. Run: ./utils/fly_deploy.sh to deploy with secrets")


def generate_secret_only():
    """Just regenerate the Flask secret key."""
    env_path = Path('.env')
    env_vars = load_env_file(env_path)

    env_vars['FLASK_SECRET_KEY'] = secrets.token_hex(32)

    save_env_file(env_path, env_vars)
    print(f"New secret key generated and saved to {env_path}")


if __name__ == '__main__':
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == '--secret-only':
        generate_secret_only()
    else:
        interactive_setup()
